# Generated by Django 3.1.6 on 2021-03-05 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_app', '0002_auto_20210227_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='expenses',
            field=models.ManyToManyField(through='savings_app.Budget', to=settings.AUTH_USER_MODEL),
        ),
    ]
