# Generated by Django 3.1.6 on 2021-03-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_app', '0003_auto_20210305_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='expenses',
            new_name='owners',
        ),
    ]
