# Generated by Django 3.1.7 on 2021-04-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_app', '0004_auto_20210305_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='modify_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
